### ISSUE TITLE
Increase size of extension bar icon

### ISSUE THREAD

**Issue by yknl** [secretkeylabs/xverse-web-extension#412]
<img width="169" alt="image" src="https://github.com/secretkeylabs/xverse-web-extension/assets/29081231/188dcafb-c53a-437c-9039-befe7dae8e1f">

**Comment by dhriaznov** [comment]
I think that's because of the black background of our logo on the dark theme of the browser because it looks the same size on the light browser theme for me:
<img width="239" alt="Monosnap Increase size of extension bar icon · Issue #412 · secretkeylabs:xverse-web-extension 2023-05-19 14-16-11" src="https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/aec3d804-260e-49f7-87ba-ea7192a5855b">

**Comment by dhriaznov** [comment]
@QUDBS what are your thoughts here?

**Comment by QUDBS** [comment]
We can slightly increase the size of the X inside the icon. But having just the X outside any shape exposes the logo to sometimes display poorly (white logo on light background for example)
<img width="227" alt="Screenshot 2023-05-19 at 14 25 03" src="https://github.com/secretkeylabs/xverse-web-extension/assets/99788136/4af78951-b532-4201-a175-4140436463d1">

**Comment by QUDBS** [comment]
Let's try with this
![32x32](https://github.com/secretkeylabs/xverse-web-extension/assets/99788136/d49fb60d-8706-4b42-88da-3f234b18d462)

**Comment by QUDBS** [comment]
Let's try with this one
![32x32](https://github.com/secretkeylabs/xverse-web-extension/assets/99788136/a01636c5-f433-466c-a5d6-4acd7aa22828)

**Comment by QUDBS** [comment]
@dhriaznov 
![128x128](https://github.com/secretkeylabs/xverse-web-extension/assets/99788136/063377b4-e913-47a5-a889-7cea66454206)
